# Generated by Django 5.1.5 on 2025-01-21 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('framework', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('private', models.BooleanField(default=False)),
                ('has_issues', models.BooleanField(default=False)),
                ('has_projects', models.BooleanField(default=True)),
                ('has_wiki', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
