# Generated by Django 4.2.7 on 2025-02-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
