# Generated by Django 4.2.7 on 2025-02-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_repo_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='testcase',
            field=models.FileField(blank=True, null=True, upload_to='testcases/'),
        ),
    ]
